# Generated by Django 5.0 on 2023-12-21 18:32

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shipping_address_line_1", models.CharField(max_length=256)),
                ("shipping_address_line_2", models.CharField(max_length=256)),
                ("shipping_country", models.CharField(max_length=128)),
                ("shipping_state_province", models.CharField(max_length=128)),
                ("shipping_city", models.CharField(max_length=128)),
                ("shipping_postal_code", models.CharField(max_length=32)),
                ("billing_address_line_1", models.CharField(max_length=256)),
                ("billing_address_line_2", models.CharField(max_length=256)),
                ("billing_country", models.CharField(max_length=128)),
                ("billing_state_province", models.CharField(max_length=128)),
                ("billing_city", models.CharField(max_length=128)),
                ("billing_postal_code", models.CharField(max_length=32)),
                ("line_total", api.models.MoneyField(decimal_places=2, max_digits=8)),
                (
                    "shipping_total",
                    api.models.MoneyField(decimal_places=2, max_digits=8),
                ),
                ("tax_total", api.models.MoneyField(decimal_places=2, max_digits=8)),
                (
                    "dicounted_total",
                    api.models.MoneyField(decimal_places=2, max_digits=8),
                ),
                ("shipped", models.BooleanField()),
                ("tracking_reference", models.CharField(max_length=128)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("products", models.ManyToManyField(to="product.product")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
